[package]
name = "limes"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["cargo", "derive"] }
ipnet = "2.10.0"
nftables = "0.4.1"
serde = "1.0.210"
serde_json = "1.0.128"
